name: solar_axis_app
description: WECE 2023-2024 EOH Project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_blue: ^0.8.0
  video_player: ^2.9.2
  webview_flutter: ^4.10.0
  webview_flutter_android: 4.3.2 # Added for Android WebView support
  webview_flutter_wkwebview: ^3.10.0 # Added for iOS WebView support
  webview_flutter_web: ^0.2.2 # Added for Web support

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - images/sunflower.png
    - images/logo.png
    - images/flower.png
